/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪探针 */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 模型名称列表 */
        get: operations["list_model_names_api_v1_models_names_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 模型族列表 */
        get: operations["list_model_families_api_v1_models_families_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 模型列表 */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        /** 注册模型 */
        post: operations["create_model_api_v1_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 幂等注册模型 */
        post: operations["upsert_model_api_v1_models_upsert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 模型详情 */
        get: operations["get_model_api_v1_models__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 后端实例列表 */
        get: operations["list_backends_api_v1_backends_get"];
        put?: never;
        /** 注册后端实例 */
        post: operations["register_backend_api_v1_backends_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backends/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量幂等注册后端实例 */
        post: operations["bulk_register_backends_api_v1_backends_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backends/{backend_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 后端实例详情 */
        get: operations["get_backend_api_v1_backends__backend_id__get"];
        put?: never;
        post?: never;
        /** 下线后端实例 */
        delete: operations["disable_backend_api_v1_backends__backend_id__delete"];
        options?: never;
        head?: never;
        /** 更新后端实例 */
        patch: operations["update_backend_api_v1_backends__backend_id__patch"];
        trace?: never;
    };
    "/api/v1/backends/{backend_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 变更实例状态 */
        post: operations["change_backend_state_api_v1_backends__backend_id__state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backends/{backend_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 实例已挂载模型 */
        get: operations["list_backend_models_api_v1_backends__backend_id__models_get"];
        /** 全量替换挂载模型 */
        put: operations["replace_backend_models_api_v1_backends__backend_id__models_put"];
        /** 挂载模型 */
        post: operations["bind_backend_models_api_v1_backends__backend_id__models_post"];
        /** 卸载模型 */
        delete: operations["unbind_backend_models_api_v1_backends__backend_id__models_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backends/{backend_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 实例健康检查历史 */
        get: operations["backend_health_history_api_v1_backends__backend_id__health_get"];
        put?: never;
        /** 上报健康检查结果 */
        post: operations["record_backend_health_api_v1_backends__backend_id__health_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 密钥列表 */
        get: operations["list_keys_api_v1_keys_get"];
        put?: never;
        /** 签发密钥 */
        post: operations["create_key_api_v1_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 校验密钥 */
        post: operations["verify_key_api_v1_keys_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 密钥详情 */
        get: operations["get_key_api_v1_keys__key_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{key_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 吊销密钥 */
        post: operations["revoke_key_api_v1_keys__key_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requests/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 请求聚合统计 */
        get: operations["request_summary_api_v1_requests_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requests/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 按时间窗口清理历史请求 */
        post: operations["purge_requests_api_v1_requests_purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 请求记录列表 */
        get: operations["list_requests_api_v1_requests_get"];
        put?: never;
        /** 写入请求记录 */
        post: operations["record_request_api_v1_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 请求记录详情 */
        get: operations["get_request_api_v1_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routing/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 候选实例打分排名 */
        get: operations["list_candidates_api_v1_routing_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyCreate */
        ApiKeyCreate: {
            /** Name */
            name: string;
            /** Scopes */
            scopes?: string[];
            /** Rate Limit Per Second */
            rate_limit_per_second?: number | string | null;
            /** Ttl Days */
            ttl_days?: number | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** ApiKeyCreatedOut */
        ApiKeyCreatedOut: {
            /** Id */
            id: number;
            /** Key Prefix */
            key_prefix: string;
            /** Name */
            name: string;
            /** Scopes */
            scopes: string[];
            /** Rate Limit Per Second */
            rate_limit_per_second?: number | null;
            /** Expires At */
            expires_at?: string | null;
            /** Revoked At */
            revoked_at?: string | null;
            /** Last Used At */
            last_used_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Key */
            key: string;
        };
        /** ApiKeyOut */
        ApiKeyOut: {
            /** Id */
            id: number;
            /** Key Prefix */
            key_prefix: string;
            /** Name */
            name: string;
            /** Scopes */
            scopes: string[];
            /** Rate Limit Per Second */
            rate_limit_per_second?: number | null;
            /** Expires At */
            expires_at?: string | null;
            /** Revoked At */
            revoked_at?: string | null;
            /** Last Used At */
            last_used_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ApiKeyVerifyIn */
        ApiKeyVerifyIn: {
            /** Key */
            key: string;
        };
        /** ApiKeyVerifyOut */
        ApiKeyVerifyOut: {
            /** Valid */
            valid: boolean;
            api_key?: components["schemas"]["ApiKeyOut"] | null;
        };
        /** BackendBulkCreate */
        BackendBulkCreate: {
            /** Items */
            items: components["schemas"]["BackendCreate"][];
        };
        /** BackendCreate */
        BackendCreate: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Engine */
            engine: string;
            /**
             * Weight
             * @default 1.000
             */
            weight: number | string;
            /**
             * Max Concurrency
             * @default 1
             */
            max_concurrency: number;
            /**
             * Cost Per Token
             * @default 0
             */
            cost_per_token: number | string;
            /** Model Ids */
            model_ids?: number[];
        };
        /** BackendOut */
        BackendOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Engine */
            engine: string;
            /** Weight */
            weight: number;
            /** Max Concurrency */
            max_concurrency: number;
            /** Cost Per Token */
            cost_per_token: number;
            /** State */
            state: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Models */
            models?: components["schemas"]["ModelOut"][] | null;
        };
        /** BackendStatOut */
        BackendStatOut: {
            /** Backend Id */
            backend_id?: number | null;
            /** Total */
            total: number;
            /** Successes */
            successes: number;
            /** Failures */
            failures: number;
            /** Avg Total Ms */
            avg_total_ms?: number | null;
            /** Avg Ttft Ms */
            avg_ttft_ms?: number | null;
        };
        /** BackendStateChange */
        BackendStateChange: {
            /** State */
            state: string;
        };
        /** BackendUpdate */
        BackendUpdate: {
            /** Url */
            url?: string | null;
            /** Weight */
            weight?: number | string | null;
            /** Max Concurrency */
            max_concurrency?: number | null;
            /** Cost Per Token */
            cost_per_token?: number | string | null;
        };
        /** CandidateListOut */
        CandidateListOut: {
            /** Model Name */
            model_name: string;
            /** Policy */
            policy: string;
            /** Ranked */
            ranked: components["schemas"]["CandidateOut"][];
        };
        /** CandidateOut */
        CandidateOut: {
            /** Backend Id */
            backend_id: number;
            /** Name */
            name: string;
            /** Weight */
            weight: number;
            /** Healthy */
            healthy: boolean | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Cost Per Token */
            cost_per_token: number;
            /** Score */
            score: number;
            /** Excluded */
            excluded: boolean;
            /** Reasons */
            reasons: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheckCreate */
        HealthCheckCreate: {
            /** Healthy */
            healthy: boolean;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Error */
            error?: string | null;
            /** Checked At */
            checked_at?: string | null;
        };
        /** HealthCheckOut */
        HealthCheckOut: {
            /** Id */
            id: number;
            /** Backend Id */
            backend_id: number;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Healthy */
            healthy: boolean;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Error */
            error?: string | null;
        };
        /** LatencyStatOut */
        LatencyStatOut: {
            /** Samples */
            samples: number;
            /** P50 Ms */
            p50_ms?: number | null;
            /** P95 Ms */
            p95_ms?: number | null;
            /** P99 Ms */
            p99_ms?: number | null;
            /** Max Ms */
            max_ms?: number | null;
        };
        /** ModelCreate */
        ModelCreate: {
            /** Name */
            name: string;
            /** Family */
            family?: string | null;
            /** Parameter Billions */
            parameter_billions?: number | string | null;
            /** Quantization */
            quantization?: string | null;
        };
        /** ModelIdsPayload */
        ModelIdsPayload: {
            /** Model Ids */
            model_ids?: number[];
        };
        /** ModelOut */
        ModelOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Family */
            family?: string | null;
            /** Parameter Billions */
            parameter_billions?: number | null;
            /** Quantization */
            quantization?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PageMeta */
        PageMeta: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
            /** Count */
            count: number;
            /** Has More */
            has_more: boolean;
        };
        /** Page[ApiKeyOut] */
        Page_ApiKeyOut_: {
            /** Items */
            items: components["schemas"]["ApiKeyOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Page[BackendOut] */
        Page_BackendOut_: {
            /** Items */
            items: components["schemas"]["BackendOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Page[ModelOut] */
        Page_ModelOut_: {
            /** Items */
            items: components["schemas"]["ModelOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Page[RequestLogOut] */
        Page_RequestLogOut_: {
            /** Items */
            items: components["schemas"]["RequestLogOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** PoolStatusOut */
        PoolStatusOut: {
            /** Size */
            size: number;
            /** Checked In */
            checked_in: number;
            /** Checked Out */
            checked_out: number;
            /** Overflow */
            overflow: number;
        };
        /** PurgeIn */
        PurgeIn: {
            /**
             * Cutoff
             * Format: date-time
             */
            cutoff: string;
            /**
             * Batch Size
             * @default 5000
             */
            batch_size: number;
        };
        /** PurgeOut */
        PurgeOut: {
            /** Deleted */
            deleted: number;
            /**
             * Cutoff
             * Format: date-time
             */
            cutoff: string;
            /** Batch Size */
            batch_size: number;
        };
        /** ReadyOut */
        ReadyOut: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Schema Version */
            schema_version?: number | null;
            pool?: components["schemas"]["PoolStatusOut"] | null;
            /** Failed */
            failed?: string[];
        };
        /** RequestLogDetailOut */
        RequestLogDetailOut: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Api Key Id */
            api_key_id?: number | null;
            /** Session Id */
            session_id?: string | null;
            /** Model Name */
            model_name: string;
            /** Backend Id */
            backend_id?: number | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Ttft Ms */
            ttft_ms?: number | null;
            /** Total Ms */
            total_ms?: number | null;
            /** Status */
            status: string;
            /** Error Code */
            error_code?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            decision?: components["schemas"]["RoutingDecisionOut"] | null;
        };
        /** RequestLogIn */
        RequestLogIn: {
            /** Model Name */
            model_name: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Request Id */
            request_id?: string | null;
            /** Api Key Id */
            api_key_id?: number | null;
            /** Session Id */
            session_id?: string | null;
            /** Backend Id */
            backend_id?: number | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Ttft Ms */
            ttft_ms?: number | string | null;
            /** Total Ms */
            total_ms?: number | string | null;
            /** Error Code */
            error_code?: string | null;
            /** Finished At */
            finished_at?: string | null;
            decision?: components["schemas"]["RoutingDecisionIn"] | null;
        };
        /** RequestLogOut */
        RequestLogOut: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Api Key Id */
            api_key_id?: number | null;
            /** Session Id */
            session_id?: string | null;
            /** Model Name */
            model_name: string;
            /** Backend Id */
            backend_id?: number | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Ttft Ms */
            ttft_ms?: number | null;
            /** Total Ms */
            total_ms?: number | null;
            /** Status */
            status: string;
            /** Error Code */
            error_code?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /** RoutingDecisionIn */
        RoutingDecisionIn: {
            /** Policy */
            policy: string;
            /** Candidate Ids */
            candidate_ids?: number[];
            /** Chosen Id */
            chosen_id?: number | null;
            /** Score Snapshot */
            score_snapshot?: {
                [key: string]: unknown;
            };
            /** Fallback Reason */
            fallback_reason?: string | null;
        };
        /** RoutingDecisionOut */
        RoutingDecisionOut: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Policy */
            policy: string;
            /** Candidate Ids */
            candidate_ids: number[];
            /** Chosen Id */
            chosen_id?: number | null;
            /** Score Snapshot */
            score_snapshot: {
                [key: string]: unknown;
            };
            /** Fallback Reason */
            fallback_reason?: string | null;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
        };
        /** StatusStatOut */
        StatusStatOut: {
            /** Status */
            status: string;
            /** Total */
            total: number;
        };
        /** SummaryOut */
        SummaryOut: {
            /** By Backend */
            by_backend: components["schemas"]["BackendStatOut"][];
            /** By Status */
            by_status: components["schemas"]["StatusStatOut"][];
            latency: components["schemas"]["LatencyStatOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    list_model_names_api_v1_models_names_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_model_families_api_v1_models_families_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: {
                family?: string | null;
                name_like?: string | null;
                /** @description 每页条数 */
                limit?: number | null;
                /** @description 偏移量 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ModelOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_model_api_v1_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_model_api_v1_models_upsert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_api_v1_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backends_api_v1_backends_get: {
        parameters: {
            query?: {
                state?: string | null;
                engine?: string | null;
                name_like?: string | null;
                with_models?: boolean;
                /** @description 每页条数 */
                limit?: number | null;
                /** @description 偏移量 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BackendOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_backend_api_v1_backends_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackendCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_register_backends_api_v1_backends_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackendBulkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backend_api_v1_backends__backend_id__get: {
        parameters: {
            query?: {
                with_models?: boolean;
            };
            header?: never;
            path: {
                backend_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_backend_api_v1_backends__backend_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_backend_api_v1_backends__backend_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackendUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_backend_state_api_v1_backends__backend_id__state_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackendStateChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backend_models_api_v1_backends__backend_id__models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_backend_models_api_v1_backends__backend_id__models_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelIdsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_backend_models_api_v1_backends__backend_id__models_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelIdsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unbind_backend_models_api_v1_backends__backend_id__models_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelIdsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backend_health_history_api_v1_backends__backend_id__health_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                backend_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_backend_health_api_v1_backends__backend_id__health_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthCheckCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_api_v1_keys_get: {
        parameters: {
            query?: {
                active_only?: boolean;
                name_like?: string | null;
                /** @description 每页条数 */
                limit?: number | null;
                /** @description 偏移量 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ApiKeyOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_key_api_v1_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_key_api_v1_keys_verify_post: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyVerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyVerifyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_key_api_v1_keys__key_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_key_api_v1_keys__key_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_summary_api_v1_requests_summary_get: {
        parameters: {
            query?: {
                started_after?: string | null;
                started_before?: string | null;
                backend_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_requests_api_v1_requests_purge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurgeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_api_v1_requests_get: {
        parameters: {
            query?: {
                backend_id?: number | null;
                api_key_id?: number | null;
                status_value?: string | null;
                model_name?: string | null;
                session_id?: string | null;
                started_after?: string | null;
                started_before?: string | null;
                failures_only?: boolean;
                /** @description 每页条数 */
                limit?: number | null;
                /** @description 偏移量 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RequestLogOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_request_api_v1_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestLogIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestLogDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_api_v1_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestLogDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_api_v1_routing_candidates_get: {
        parameters: {
            query: {
                model_name: string;
                policy?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
